#!/bin/bash
#
# Node1

NORTHSEED="172.17.0.2"

docker run -it -d -v /home/felipemendes/scylla-enterprise/south/rack1/:/etc/scylla/ \
       --name south1 -h south1 scylladb/scylla-enterprise:latest --cpuset 0 --smp 1   \
       --memory 800M --seeds=south1,${NORTHSEED}

# Retrieve south1 IP
sleep 5
SEEDIP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' south1)
echo "South1 IP is: $SEEDIP"

# Create node2 and node3
docker run -it -d -v /home/felipemendes/scylla-enterprise/south/rack2/:/etc/scylla/ \
        --name south2 scylladb/scylla-enterprise:latest --cpuset 1 --smp 1  \
        --memory 800M --seeds=${SEEDIP},${NORTHSEED} 

docker run -it -d -v /home/felipemendes/scylla-enterprise/south/rack3/:/etc/scylla/ \
        --name south3 scylladb/scylla-enterprise:latest --cpuset 2 --smp 1  \
        --memory 800M --seeds=${SEEDIP},${NORTHSEED}
