#!/bin/bash

# Retrieve node1 and south1 IPs
NORTHIP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' node1)
SOUTHIP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' south1)

# Perform updates
for i in node1 node2 node3 south1 south2 south3; do

   docker exec $i sed -i "s/seeds=.*\s/seeds=${NORTHIP},${SOUTHIP} /g" /etc/scylla.d/docker.conf
   echo "${i}: "
   docker exec $i cat /etc/scylla.d/docker.conf 
done

# Restart all cluster
echo "Restarting cluster, this will wait 30 seconds for EACH node. Grab a coffee :-)"

for i in node1 node2 node3 south1 south2 south3; do
   docker stop $i
   docker start $i
   sleep 30
done
