version: '3'

services:
  scylla-manager:
    image: scylladb/scylla-manager:2.3.0
    container_name: scylla-manager
    network_mode: "bridge"
    external_links:
      - scylla-manager-db
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla
    container_name: scylla-manager-db
    network_mode: "bridge"
